version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/pdns-mysql"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/pdns-recursor"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/pdns-admin"
    schedule:
      interval: "monthly"
